default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: MeetupPlanner_development
  host: localhost
  username: Silo
  password:

test:
  <<: *default
  database: MeetupPlanner_test
  host: localhost
  username: Silo
  password:

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>