default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: MeetupPlanner_development

test:
  <<: *default
  database: MeetupPlanner_test

production:
  <<: *default
  database: MeetupPlanner_production
  username: MeetupPlanner
  password: <%= ENV['MEETUPPLANNER_DATABASE_PASSWORD'] %>
